DROP TABLE IF EXISTS MAHASISWA;
  
CREATE TABLE MAHASISWA (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  nim VARCHAR(250) NOT NULL,
  name VARCHAR(250) NOT NULL
);

DROP TABLE IF EXISTS CLASS_SCHEDULE;

CREATE TABLE CLASS_SCHEDULE (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  code VARCHAR(250) NOT NULL,
  name VARCHAR(250) NOT NULL,
  date date,
  mahasiswa_fk VARCHAR(250)
);